# Generated by Django 5.2.8 on 2025-12-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carouselslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_title', models.CharField(default='Une approche dédiée à votre bien-être', max_length=200)),
                ('intro_text', models.TextField(default='Chaque séance est une invitation au lâcher-prise...')),
                ('cta_title', models.CharField(default='Prêt(e) à vous accorder une pause ?', max_length=200)),
                ('cta_text', models.TextField(default="N'attendez plus pour prendre soin de vous...")),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField(default=True, help_text="Afficher ce témoignage sur la page d'accueil")),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
