# Generated by Django 5.2.8 on 2025-12-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homepagecontent_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mon approche du bien-être', max_length=200)),
                ('main_text', models.TextField(default='Passionnée par les thérapies manuelles...')),
                ('philosophy_text', models.TextField(default='Ma philosophie repose sur une écoute attentive...')),
                ('commitments_title', models.CharField(default='Mes engagements pour votre sérénité', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Image pour la page À Propos', null=True, upload_to='about/')),
            ],
        ),
    ]
