# Generated by Django 5.2.8 on 2025-12-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_commitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='testimonials_title',
            field=models.CharField(default='Ce que mes client(e)s en disent', max_length=200),
        ),
    ]
