# Generated by Django 5.2.8 on 2025-12-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_homepagecontent_testimonials_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Prenons contact', max_length=200)),
                ('subtitle', models.TextField(default='Pour toute question ou pour prendre rendez-vous...')),
                ('email_title', models.CharField(default='Email', max_length=100)),
                ('email', models.EmailField(default='contact@bienetre.com', max_length=254)),
                ('phone_title', models.CharField(default='Téléphone', max_length=100)),
                ('phone', models.CharField(default='06 12 34 56 78', max_length=50)),
                ('address_title', models.CharField(default='Adresse', max_length=100)),
                ('address', models.CharField(default='Paris, France', max_length=200)),
            ],
        ),
    ]
