# Generated by Django 5.2.8 on 2025-12-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contactpagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Découvrez nos soins', max_length=200)),
                ('subtitle', models.TextField(default='Une gamme de massages conçus pour répondre à vos attentes et vous procurer une détente optimale.')),
            ],
        ),
    ]
