# Generated by Django 5.2.8 on 2025-12-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_servicepagecontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePageContent',
        ),
    ]
