# Generated by Django 5.2.8 on 2026-01-01 07:33

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
